# Generated by Django 3.1 on 2020-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='No',
            field=models.IntegerField(),
        ),
    ]
